/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package paintbasico;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Point;
import java.awt.Shape;
import java.awt.geom.Ellipse2D;
import java.awt.geom.Line2D;
import java.awt.geom.Rectangle2D;

/**
 *
 * @author Usuario
 */
public class Lienzo extends javax.swing.JPanel {
    Shape forma = new Line2D.Float(0,0,0,0);
    public enum tipo { LINEA, RECTANGULO, ELIPSE};
    private Color color = Color.black;
    private boolean relleno=false;
    private Point punto;
    public tipo formaSeleccionada = tipo.LINEA;
    
    public void setColor(Color color) {
        this.color = color;
    }

    public Color getColor() {
        return color;
    }
    
    public void setForma(tipo forma) {
    this.formaSeleccionada = forma;
    }
    
    public void setRelleno(boolean relleno) {
        this.relleno = relleno;
    }

    public boolean getRelleno() {
        return relleno;
    }
    
    /**
     * Creates new form Lienzo
     */
    public Lienzo() {
        initComponents();
    }
    
    @Override
    public void paint(Graphics g){
    super.paint(g);
    Graphics2D g2d = (Graphics2D)g;
    g2d.setPaint(color);
    if (this.getRelleno()== true)
    {
        g2d.fill(forma);
    }
    g2d.draw(forma);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        punto = evt.getPoint();
        switch(formaSeleccionada) {
            case LINEA -> forma = new Line2D.Float(evt.getPoint(), evt.getPoint());
            case RECTANGULO -> forma = new Rectangle2D.Float();
            case ELIPSE -> forma = new Ellipse2D.Float();
        }
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        switch(formaSeleccionada) {
            case LINEA -> ((Line2D)forma).setLine(((Line2D)forma).getP1(), evt.getPoint());
            case RECTANGULO -> ((Rectangle2D)forma).setFrameFromDiagonal(punto, evt.getPoint());
            case ELIPSE -> ((Ellipse2D)forma).setFrameFromDiagonal(punto, evt.getPoint());
        }
        this.repaint();
    }//GEN-LAST:event_formMouseDragged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
