/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package paintbasico;

import java.awt.Color;
import javax.swing.ImageIcon;
import SMM.MUM.graficos.*;
import java.awt.image.BufferedImage;
import javax.swing.event.InternalFrameAdapter;

/**
 *
 * @author Usuario
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    //MumLienzo lienzo1 = getSelectedLienzo();
    public VentanaPrincipal() {
        initComponents();
        setTitle("Paint Básico");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Botonlinea = new javax.swing.JButton();
        BotonRectangulo = new javax.swing.JButton();
        BotonElipse = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        Relleno = new javax.swing.JCheckBox();
        color_negro = new javax.swing.JButton();
        color_blanco = new javax.swing.JButton();
        color_amarillo = new javax.swing.JButton();
        color_azul = new javax.swing.JButton();
        color_rojo = new javax.swing.JButton();
        color_verde = new javax.swing.JButton();
        mover = new javax.swing.JCheckBox();
        transparencia = new javax.swing.JCheckBox();
        Stroke = new javax.swing.JSpinner();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        Archivo = new javax.swing.JMenu();
        nuevo_menu = new javax.swing.JMenuItem();
        abrir_menu = new javax.swing.JMenuItem();
        guardar_menu = new javax.swing.JMenuItem();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Botonlinea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/linea.png"))); // NOI18N
        Botonlinea.setToolTipText("Linea");
        Botonlinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonlineaActionPerformed(evt);
            }
        });

        BotonRectangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/rectangulo.png"))); // NOI18N
        BotonRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRectanguloActionPerformed(evt);
            }
        });

        BotonElipse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/elipse.png"))); // NOI18N
        BotonElipse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonElipseActionPerformed(evt);
            }
        });

        Relleno.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        Relleno.setText("Relleno");
        Relleno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RellenoActionPerformed(evt);
            }
        });

        color_negro.setBackground(new java.awt.Color(0, 0, 0));
        color_negro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                color_negroActionPerformed(evt);
            }
        });

        color_blanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                color_blancoActionPerformed(evt);
            }
        });

        color_amarillo.setBackground(new java.awt.Color(255, 255, 0));
        color_amarillo.setForeground(new java.awt.Color(255, 255, 255));
        color_amarillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                color_amarilloActionPerformed(evt);
            }
        });

        color_azul.setBackground(new java.awt.Color(51, 51, 255));
        color_azul.setToolTipText("");
        color_azul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                color_azulActionPerformed(evt);
            }
        });

        color_rojo.setBackground(new java.awt.Color(255, 0, 0));
        color_rojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                color_rojoActionPerformed(evt);
            }
        });

        color_verde.setBackground(new java.awt.Color(0, 255, 0));
        color_verde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                color_verdeActionPerformed(evt);
            }
        });

        mover.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        mover.setText("Mover");
        mover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moverActionPerformed(evt);
            }
        });

        transparencia.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        transparencia.setText("Transparencia");
        transparencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transparenciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(color_negro, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(color_rojo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(color_azul, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(color_blanco, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(color_amarillo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(color_verde, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(Stroke, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(transparencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mover, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Relleno)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(color_negro, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(color_azul, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(color_rojo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(color_blanco, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(color_amarillo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(color_verde, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Relleno)
                    .addComponent(mover)
                    .addComponent(transparencia)
                    .addComponent(Stroke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Botonlinea, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonElipse, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Botonlinea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(BotonRectangulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotonElipse, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("Barra de estado");
        jPanel3.add(jLabel2, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 522, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 188, Short.MAX_VALUE)
        );

        getContentPane().add(escritorio, java.awt.BorderLayout.CENTER);

        Archivo.setText("Archivo");

        nuevo_menu.setText("Nuevo");
        nuevo_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevo_menuActionPerformed(evt);
            }
        });
        Archivo.add(nuevo_menu);

        abrir_menu.setText("Abrir");
        Archivo.add(abrir_menu);

        guardar_menu.setText("Guardar");
        Archivo.add(guardar_menu);

        jMenuBar1.add(Archivo);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private MumLienzo getSelectedLienzo() {
        VentanaInterna vi;
        vi = (VentanaInterna) escritorio.getSelectedFrame();
        return vi != null ? vi.getLienzo1() : null;
    }

    private void nuevo_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevo_menuActionPerformed
    VentanaInterna vi = new VentanaInterna();
    escritorio.add(vi);
    vi.setVisible(true);
    
    //Crear objeto manejador y enlazarlo con la funcion manejadora
    vi.addInternalFrameListener( new ManejadorVentanaInterna());
    
    BufferedImage img;
    img = new BufferedImage(300,300,BufferedImage.TYPE_INT_RGB);
    vi.getLienzo1().setImage(img);
    }//GEN-LAST:event_nuevo_menuActionPerformed

    private void BotonlineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonlineaActionPerformed
        MumLienzo lienzo1 = getSelectedLienzo();
        if (lienzo1 != null){
            lienzo1.setForma(MumLienzo.tipo.LINEA);
        }
    }//GEN-LAST:event_BotonlineaActionPerformed

    private void BotonElipseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonElipseActionPerformed
        MumLienzo lienzo1 = getSelectedLienzo();
        if (lienzo1 != null){
            lienzo1.setForma(MumLienzo.tipo.ELIPSE);
        }
    }//GEN-LAST:event_BotonElipseActionPerformed

    private void BotonRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRectanguloActionPerformed
        MumLienzo lienzo1 = getSelectedLienzo();
        if (lienzo1 != null){
            lienzo1.setForma(MumLienzo.tipo.RECTANGULO);
        }
    }//GEN-LAST:event_BotonRectanguloActionPerformed

    private void RellenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RellenoActionPerformed
        MumLienzo lienzo1 = getSelectedLienzo();
        if (lienzo1 != null){
            lienzo1.setRelleno(Relleno.isSelected());
        }
    }//GEN-LAST:event_RellenoActionPerformed

    private void color_negroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_color_negroActionPerformed
        MumLienzo lienzo1 = getSelectedLienzo();
        if (lienzo1 != null){
            lienzo1.setColor(Color.black);
        }
    }//GEN-LAST:event_color_negroActionPerformed

    private void color_blancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_color_blancoActionPerformed
        MumLienzo lienzo1 = getSelectedLienzo();
        if (lienzo1 != null){
            lienzo1.setColor(Color.white);
        }
    }//GEN-LAST:event_color_blancoActionPerformed

    private void color_rojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_color_rojoActionPerformed
        MumLienzo lienzo1 = getSelectedLienzo();
        if (lienzo1 != null){
            lienzo1.setColor(Color.red);
        }
    }//GEN-LAST:event_color_rojoActionPerformed

    private void color_amarilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_color_amarilloActionPerformed
        MumLienzo lienzo1 = getSelectedLienzo();
        if (lienzo1 != null){
            lienzo1.setColor(Color.yellow);
        }
    }//GEN-LAST:event_color_amarilloActionPerformed

    private void color_azulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_color_azulActionPerformed
        MumLienzo lienzo1 = getSelectedLienzo();
        if (lienzo1 != null){
            lienzo1.setColor(Color.blue);
        }
    }//GEN-LAST:event_color_azulActionPerformed

    private void color_verdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_color_verdeActionPerformed
        MumLienzo lienzo1 = getSelectedLienzo();
        if (lienzo1 != null){
            lienzo1.setColor(Color.green);
        }    
    }//GEN-LAST:event_color_verdeActionPerformed

    private void moverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moverActionPerformed
            MumLienzo lienzo1 = getSelectedLienzo();
        if (lienzo1 != null){
            lienzo1.setMover(mover.isSelected());
        }        
    }//GEN-LAST:event_moverActionPerformed

    private void transparenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transparenciaActionPerformed
        MumLienzo lienzo1 = getSelectedLienzo();
        if (lienzo1 != null){
            lienzo1.setTransparencia(transparencia.isSelected()); 
        }   
    }//GEN-LAST:event_transparenciaActionPerformed

    private class ManejadorVentanaInterna extends InternalFrameAdapter{
        public void InternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            VentanaInterna vi = (VentanaInterna)evt.getInternalFrame();
            Relleno.setSelected(vi.getLienzo1().getRelleno());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Archivo;
    private javax.swing.JButton BotonElipse;
    private javax.swing.JButton BotonRectangulo;
    private javax.swing.JButton Botonlinea;
    private javax.swing.JCheckBox Relleno;
    private javax.swing.JSpinner Stroke;
    private javax.swing.JMenuItem abrir_menu;
    private javax.swing.JButton color_amarillo;
    private javax.swing.JButton color_azul;
    private javax.swing.JButton color_blanco;
    private javax.swing.JButton color_negro;
    private javax.swing.JButton color_rojo;
    private javax.swing.JButton color_verde;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuItem guardar_menu;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JCheckBox mover;
    private javax.swing.JMenuItem nuevo_menu;
    private javax.swing.JCheckBox transparencia;
    // End of variables declaration//GEN-END:variables
}
